/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GuidesSlugRouteImport } from './routes/guides.$slug'
import { Route as ApiPublicSendLeadRouteImport } from './routes/api/public/send-lead'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesSlugRoute = GuidesSlugRouteImport.update({
  id: '/guides/$slug',
  path: '/guides/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSendLeadRoute = ApiPublicSendLeadRouteImport.update({
  id: '/api/public/send-lead',
  path: '/api/public/send-lead',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/api/public/send-lead': typeof ApiPublicSendLeadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/api/public/send-lead': typeof ApiPublicSendLeadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/api/public/send-lead': typeof ApiPublicSendLeadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/guides/$slug' | '/api/public/send-lead'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/guides/$slug' | '/api/public/send-lead'
  id: '__root__' | '/' | '/guides/$slug' | '/api/public/send-lead'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GuidesSlugRoute: typeof GuidesSlugRoute
  ApiPublicSendLeadRoute: typeof ApiPublicSendLeadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/$slug': {
      id: '/guides/$slug'
      path: '/guides/$slug'
      fullPath: '/guides/$slug'
      preLoaderRoute: typeof GuidesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/send-lead': {
      id: '/api/public/send-lead'
      path: '/api/public/send-lead'
      fullPath: '/api/public/send-lead'
      preLoaderRoute: typeof ApiPublicSendLeadRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GuidesSlugRoute: GuidesSlugRoute,
  ApiPublicSendLeadRoute: ApiPublicSendLeadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
